export enum JSON_ACTION_TYPES {
  SET_DEFAULT_JSON = 'SET_DEFAULT_JSON',
  SET_DEFAULT_JSON_DONE = 'SET_DEFAULT_JSON_DONE',
  SET_DEFAULT_JSON_SUCCESS = 'SET_DEFAULT_JSON_SUCCESS',
  SET_DEFAULT_JSON_FAILED = 'SET_DEFAULT_JSON_FAILED',
  SET_JSON_START = 'SET_JSON_START',
  SET_JSON_DONE = 'SET_JSON_DONE',
  SET_JSON_SUCCESS = 'SET_JSON_SUCCESS',
  SET_JSON_FAILED = 'SET_JSON_FAILED',
}
